# Generated by Django 2.1.4 on 2018-12-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_remove_url_shortened_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
