# Generated by Django 2.1.4 on 2018-12-23 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='shortened_url',
        ),
    ]
