# Generated by Django 2.1.4 on 2018-12-24 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_auto_20181224_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='user_url',
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
